In [1]:
# Import dependencies
from citipy import citipy
import requests
import json
import pandas as pd
import gmaps

# Google developer API key
from config import g_key

# Access maps with unique API key
gmaps.configure(api_key=g_key)

In [2]:
# Import Weather.csv
df = pd.read_csv('output/WeatherPy.csv')
df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Simple_Date
0,0,Dikson,73.5069,80.5464,12.88,89,95,18.19,RU,1634968857,2021-10-23
1,1,New Norfolk,-42.7826,147.0587,55.65,84,100,1.66,AU,1634969004,2021-10-23
2,2,Slave Lake,55.2834,-114.7690,41.50,56,100,9.66,CA,1634969005,2021-10-23
3,3,Hasaki,35.7333,140.8333,64.80,47,32,19.26,JP,1634968833,2021-10-23
4,4,Aleksandrovsk-Sakhalinskiy,50.8975,142.1561,41.34,73,86,11.30,RU,1634969007,2021-10-23

In [29]:
# creating coordinates and humidity variables for heatmap_layer
coordinates = df[["Lat","Lng"]]
humidity = df["Humidity"]

In [30]:
# Create a heat map that displays the humidity for every city from the part I of the homework.

# Customize the size of the figure
figure_layout = {
    'width': '800px',
    'height': '600px'
}
fig = gmaps.figure(layout=figure_layout)

# Create heatmap
heatmap_layer = gmaps.heatmap_layer(locations = coordinates,weights = humidity)
fig.add_layer(heatmap_layer)
fig

Figure(layout=FigureLayout(height='600px', width='800px'))

In [3]:
# narrowing down DataFrame to find ideal weather condition
ideal_weather_df = df[(df["Max Temp"] > 70) & (df["Max Temp"] < 80) & (df["Wind Speed"] < 10) & (df["Cloudiness"] == 0)]
ideal_weather_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Simple_Date
161,161,Sao Filipe,14.8961,-24.4956,79.05,70,0,5.26,CV,1634969143,2021-10-23
267,267,Kang,-23.6752,22.7876,71.44,14,0,9.57,BW,1634969044,2021-10-23
315,315,Adrar,27.8743,-0.2939,70.70,45,0,7.40,DZ,1634968835,2021-10-23
418,418,Rio Branco,-9.9747,-67.8100,79.41,89,0,6.91,BR,1634969216,2021-10-23
458,458,Taoudenni,22.6783,-3.9836,74.88,30,0,6.17,ML,1634969417,2021-10-23
482,482,Dekar,-21.5333,21.9333,75.56,12,0,9.13,BW,1634969440,2021-10-23
502,502,Vao,-22.6667,167.4833,73.63,79,0,7.56,NC,1634969460,2021-10-23
525,525,Agadez,19.7500,10.2500,76.57,19,0,8.05,NE,1634969483,2021-10-23
553,553,Asansol,23.6833,86.9833,79.70,45,0,3.85,IN,1634969511,2021-10-23

In [113]:
# Use Google Places API to find the first hotel for each city located within 5000 meters of your coordinates.

# creating a list of lat and lng for  request loop
target_coordinates = ideal_weather_df["Lat"].astype(str) + "%2C" + ideal_weather_df["Lng"].astype(str)

# create empty lists for for loop
name = []
city = []
hotel_lat = []
hotel_lng = []

for i in target_coordinates:
    response = requests.get(f'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={i}&radius=5000&type=hotel&key={g_key}').json()
    try:
        name.append(json.dumps(response["results"][2]["name"]))
        city.append(json.dumps(response["results"][2]["vicinity"]))
        hotel_lat.append(json.dumps(response["results"][1]["geometry"]["location"]["lat"]))
        hotel_lng.append(json.dumps(response["results"][1]["geometry"]["location"]["lng"]))
    except:
        pass

# create hotel_df for heatmap
hotel_df = pd.DataFrame({
    "name": name,
    "city": city,
    "hotel_lat": hotel_lat,
    "hotel_lng": hotel_lng
})

In [116]:
# Plot the hotels on top of the humidity heatmap with each pin containing ***hotel info (can't figure out how to add more than one line)
figure_layout = {
    'width': '800px',
    'height': '600px'
}
fig = gmaps.figure(layout=figure_layout)
heatmap_layer = gmaps.heatmap_layer(locations = coordinates,weights = humidity)
marker_locations = hotel_df[["hotel_lat","hotel_lng"]].astype(float)
marker_box = hotel_df["name"] 
markers = gmaps.marker_layer(marker_locations, hover_text =marker_box, display_info_box=None)
fig.add_layer(heatmap_layer)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='600px', width='800px'))